name = "Mongoc"
uuid = "4fe8b98c-fc19-5c23-8ec2-168ff83495f2"
license = "MIT"
authors = ["Felipe Noronha <felipenoris@gmail.com>"]
repo = "https://github.com/felipenoris/Mongoc.jl.git"
version = "0.6.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
MongoC_jll = "90100e71-7732-535a-9be7-2e9affd1cfc1"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
MongoC_jll = "1.16.2"
julia = "1.3"

[extras]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Distributed"]
